---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pypi
  namespace: infrastructure
  labels:
    type: local
    app: pypi
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/kubernetes/pypi
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypi
  namespace: infrastructure
  labels:
    app: pypi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypi
  namespace: infrastructure
  labels:
    app: pypi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypi
  template:
    metadata:
      labels:
        app: pypi
    spec:
      initContainers:
      - name: permission-fix
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /packages"]
        volumeMounts:
        - name: pypi
          mountPath: /packages
      containers:
      - name: pypi
        image: pypiserver/pypiserver:latest
        args: ["-P", ".", "-a", "."]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pypi
          mountPath: /home/pypiserver/packages
      volumes:
      - name: pypi
        persistentVolumeClaim:
          claimName: pypi
---
apiVersion: v1
kind: Service
metadata:
  name: pypi
  namespace: infrastructure
  labels:
    app: pypi
spec:
  ports:
  - name: pypi
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: pypi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pypi
  namespace: infrastructure
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - secretName: home
  rules:
  - host: pypi.home.local
    http:
      paths:
      - path: /
        backend:
          serviceName: pypi
          servicePort: 8080
